version: 2

sources:
  - name: adventure_works
    description: This is a replica of the Postgres database used by our client
    tables:
      - name: salesreason
        description: This table contains information about the order

      - name: salesorderdetail
        description: 'Individual products associated with a specific sales order. See SalesOrderHeader.'

      - name: personcreditcard
        description: 'Cross-reference table mapping people to their credit card information in the CreditCard table.'

      - name: salesorderheadersalesreason
        description: 'Cross-reference table mapping sales orders to sales reason codes.'

      - name: customer
        description: 'Current customer information. Also see the Person and Store tables.'

      - name: creditcard
        description: 'Customer credit card information.'

      - name: salesorderheader
        description: 'General sales order information.'

      - name: currencyrate
        description: 'Currency exchange rates.'

      - name: address
        description: 'Table with the address information'

      - name: stateprovince
        description: 'Table with the stateprovince information'

      - name: countryregion
        description: 'Table with the country information'

      - name: person
        description: 'Table with the person information'

      - name: product
        description: 'Table with the products information'

      - name: businessentitycontact
        description: 'Table with the businessentity information'

    