version: 2

sources:
  - name: adventure_works
    description: This is a replica of the Postgres database used by our client
    tables:
      - name: salesreason
        description: 'Essa tabela contem informações associadas ao motivo do pedido'

      - name: salesorderdetail
        description: 'Esta tabela contém as informações individuais dos produtos em cada pedido.'

      - name: personcreditcard
        description: 'Tabela que referencia determinada pessoa com determinado cartão.'

      - name: salesorderheadersalesreason
        description: 'Faz a relação entre a salesorderheader com salesreason'

      - name: customer
        description: 'Tabela de clientes.'

      - name: creditcard
        description: 'Tabela de informações de cartão de crédito'

      - name: salesorderheader
        description: 'Informações de venda POR PEDIDO'

      - name: address
        description: 'Tabela com os endereços e códigos'

      - name: stateprovince
        description: 'Tabela com os estados'

      - name: countryregion
        description: 'Tabela com os países e seus códigos'

      - name: person
        description: 'Tabela com informações de pessoas'

      - name: product
        description: 'Tabela com informação de produto'

      - name: businessentitycontact
        description: 'Tabela não utilizada'

    